# Generated by Django 4.2.3 on 2023-08-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_toClient',
            field=models.BooleanField(default=False),
        ),
    ]
