# Generated by Django 4.2.3 on 2023-08-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_lead_converted_toclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='converted_toClient',
            new_name='converted_to_client',
        ),
    ]
